In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("../data/data.csv")

In [3]:
df

      variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

#### convert to independent and dependent variables

In [4]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [5]:
X.head()

   variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=47)

In [7]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

ValueError: Unknown label type: 'continuous-multioutput'

In [8]:
y_train

      variance  skewness  curtosis   entropy
757    2.66060    3.1681   1.96190  0.186620
1019  -0.81720    3.3812  -3.66840 -3.456000
404    0.37980    0.7098   0.75720 -0.444400
58     3.13770   -4.1096   4.57010  0.989630
731    1.01820    9.1090  -0.62064 -1.712900
...        ...       ...       ...       ...
691    0.57060   -0.0248   1.24210 -0.562100
584    0.33565    6.8369   0.69718 -0.556910
1288  -2.65900   -1.6058   1.36470  0.164640
327    4.21640    9.4607  -4.92880 -5.236600
1159  -2.56500   -5.7899   6.01220  0.046968

[960 rows x 4 columns]

In [11]:
y_test

      variance  skewness  curtosis  entropy
771  -0.985400  -6.66100   5.82450  0.54610
480   0.947320  -0.57113   7.19030 -0.67587
751   2.254600   8.09920  -0.24877 -3.26980
1326 -1.294300   2.67350  -0.84085 -2.03230
953  -0.092194   0.39315  -0.32846 -0.13794
...        ...       ...       ...      ...
69    0.123260   8.98480  -0.93510 -2.43320
400   1.304900  -0.15521   6.49110 -0.75346
189   2.736500  -5.03250   6.66080 -0.57889
24    4.433800   9.88700  -4.67950 -3.74830
29    4.890600  -3.35840   3.42020  1.09050

[412 rows x 4 columns]